In [1]:
print("Hello World")

Hello World


In [2]:
# creating numpy/ n-d arrays
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2=np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [8]:
arr3=np.zeros((2,3))
print(arr3)
type(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


numpy.ndarray

In [9]:
arr4=np.ones((3,3))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr5=np.identity(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
arr6=np.arange(3,100,3)
print(arr6)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [12]:
arr7=np.linspace(1,5,3)
print(arr7)

[1. 3. 5.]


In [13]:
arr8=np.array([[1,2,3],[4,5,6]])
print(arr8.shape)
print(arr8.ndim)

(2, 3)
2


In [16]:
print(arr8.size)
arr8.itemsize

6


4

In [17]:
print(arr8.dtype)

int32


In [18]:
arr9=np.array([1.0,2.4])

In [19]:
print(arr9.dtype)

float64


In [21]:
print(arr8.dtype)
arr8=arr8.astype('float')
print(arr8.dtype)

int32
float64
